ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 4433
    onOpen: ignore
tasks:
  - init:  docker-compose pull
  - name: Start Dockware
    command: docker-compose up -d
