ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 443
    onOpen: ignore
tasks:
  - init:  docker-compose pull
  - name: Start Dockware
    command: docker run --rm -p 8000:80 dockware/play:latest;
